import { getSupabase } from "../lib/supabase";
import { assertScoreManifest, type AttemptEvent,type AttemptResult,type Exercise,type ProgressSummary,type ScoreManifest,type LearningApiError } from "./contracts";
export class LearningClientError extends Error { constructor(message:string,readonly status:number,readonly code:string,readonly retryable:boolean){super(message);} }
export interface LearningApi { manifest(songId:string,signal?:AbortSignal):Promise<ScoreManifest>; exercises(songId:string,signal?:AbortSignal):Promise<Exercise[]>; evaluate(exerciseId:string,events:AttemptEvent[],idempotencyKey:string,signal?:AbortSignal):Promise<AttemptResult>; saveProgress(summary:ProgressSummary,signal?:AbortSignal):Promise<void>; }
const sleep=(ms:number,signal?:AbortSignal)=>new Promise<void>((resolve,reject)=>{const id=setTimeout(resolve,ms);signal?.addEventListener("abort",()=>{clearTimeout(id);reject(new DOMException("Aborted","AbortError"));},{once:true});});
export class LearningApiClient implements LearningApi {
 constructor(private baseUrl:string,private timeoutMs=10_000){}
 private async request<T>(path:string,init:RequestInit={},auth=false):Promise<T>{let last:unknown;for(let attempt=0;attempt<3;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);init.signal?.addEventListener("abort",()=>controller.abort(),{once:true});try{const headers=new Headers(init.headers);headers.set("Accept","application/json");headers.set("Content-Type","application/json");headers.set("X-Learning-Api-Version","v1");if(auth){const session=(await getSupabase()?.auth.getSession())?.data.session;if(session)headers.set("Authorization",`Bearer ${session.access_token}`);}const response=await fetch(`${this.baseUrl.replace(/\/$/,"")}/v1${path}`,{...init,headers,signal:controller.signal});if(response.ok)return (response.status===204?undefined:await response.json()) as T;const body=await response.json().catch(()=>({code:"http_error",message:response.statusText})) as LearningApiError;const retryable=response.status===429||response.status>=500;if(!retryable)throw new LearningClientError(body.message,response.status,body.code,false);last=new LearningClientError(body.message,response.status,body.code,true);}catch(error){last=error;if(error instanceof LearningClientError&&!error.retryable)throw error;}finally{clearTimeout(timer);}if(attempt<2)await sleep(250*2**attempt,init.signal??undefined);}throw last instanceof Error?last:new LearningClientError("Learning API unavailable",0,"unavailable",true);}
 manifest=async(id:string,s?:AbortSignal)=>assertScoreManifest(await this.request<unknown>(`/songs/${encodeURIComponent(id)}/manifest`,{signal:s}));
 exercises=(id:string,s?:AbortSignal)=>this.request<Exercise[]>(`/songs/${encodeURIComponent(id)}/exercises`,{signal:s});
 evaluate=(id:string,events:AttemptEvent[],key:string,s?:AbortSignal)=>this.request<AttemptResult>(`/exercises/${encodeURIComponent(id)}/attempts`,{method:"POST",body:JSON.stringify({events}),headers:{"Idempotency-Key":key},signal:s},true);
 saveProgress=(summary:ProgressSummary,s?:AbortSignal)=>this.request<void>(`/progress/${encodeURIComponent(summary.songId)}`,{method:"PUT",body:JSON.stringify(summary),signal:s},true);
}
