import type { FingeringCandidate,NoteEvent } from "./contracts";
export type NoteState="active"|"upcoming"|"correct"|"missed"|"wrong";
export interface TimelineVisualizer{mount():void;render(active:NoteEvent[],upcoming:NoteEvent[],states?:Map<number,NoteState>):void;destroy():void;}
export class Piano88Visualizer implements TimelineVisualizer{constructor(private root:HTMLElement){}mount(){this.root.classList.add("learning-piano");this.root.innerHTML=Array.from({length:88},(_,i)=>{const midi=i+21,black=[1,3,6,8,10].includes(midi%12);return `<span class="learning-key ${black?"black":"white"}" data-note="${midi}" role="img" aria-label="MIDI note ${midi}"></span>`;}).join("");}render(active:NoteEvent[],upcoming:NoteEvent[],states=new Map()){const a=new Set(active.map(n=>n.midi)),u=new Set(upcoming.map(n=>n.midi));this.root.querySelectorAll<HTMLElement>("[data-note]").forEach(k=>{const n=Number(k.dataset.note);k.className=`learning-key ${[1,3,6,8,10].includes(n%12)?"black":"white"} ${a.has(n)?"active":""} ${u.has(n)?"upcoming":""} ${states.get(n)??""}`;});}destroy(){this.root.replaceChildren();}}
export interface GuitarConfig{tuning:number[];frets:number;}
export function guitarCandidates(note:NoteEvent,config:GuitarConfig={tuning:[40,45,50,55,59,64],frets:20}):FingeringCandidate[]{if(note.string&&note.fret!==undefined)return[{instrument:"guitar",noteId:note.id,rank:1,confidence:"explicit",string:note.string,fret:note.fret,reason:"Explicit score fingering"}];return config.tuning.map((open,i)=>({string:i+1,fret:note.midi-open})).filter(x=>x.fret>=0&&x.fret<=config.frets).sort((a,b)=>a.fret-b.fret).map((x,i)=>({instrument:"guitar",noteId:note.id,rank:i+1,confidence:"suggestion",...x,reason:"Playable candidate; not authoritative"}));}
export class GuitarVisualizer implements TimelineVisualizer{constructor(private root:HTMLElement,private config:GuitarConfig={tuning:[40,45,50,55,59,64],frets:20}){}mount(){this.root.classList.add("learning-fretboard");this.root.innerHTML=this.config.tuning.map((_,s)=>`<div class="guitar-string" data-string="${s+1}">${Array.from({length:this.config.frets+1},(_,f)=>`<span data-fret="${f}">${f}</span>`).join("")}</div>`).join("");}render(active:NoteEvent[]){this.root.querySelectorAll(".active").forEach(e=>e.classList.remove("active"));active.flatMap(n=>guitarCandidates(n,this.config).slice(0,1)).forEach(c=>this.root.querySelector(`[data-string="${c.string}"] [data-fret="${c.fret}"]`)?.classList.add("active"));}destroy(){this.root.replaceChildren();}}
export interface AccordionConfig{rightHandMidi:number[];bassButtons:Array<{id:string;midi:number}>;}
export class AccordionVisualizer implements TimelineVisualizer{constructor(private root:HTMLElement,private config:AccordionConfig){ }mount(){this.root.classList.add("learning-accordion");this.root.innerHTML=`<div>${this.config.rightHandMidi.map(n=>`<span data-note="${n}">${n}</span>`).join("")}</div><div>${this.config.bassButtons.map(b=>`<span data-note="${b.midi}">${b.id}</span>`).join("")}</div>`;}render(active:NoteEvent[],upcoming:NoteEvent[]){const a=new Set(active.map(n=>n.midi)),u=new Set(upcoming.map(n=>n.midi));this.root.querySelectorAll<HTMLElement>("[data-note]").forEach(e=>{const n=Number(e.dataset.note);e.classList.toggle("active",a.has(n));e.classList.toggle("upcoming",u.has(n));});}destroy(){this.root.replaceChildren();}}
