import pkg from "@tonejs/midi";
import { describe, expect, it } from "vitest";
import { alignLyricsToNotes } from "./lyrics-alignment";
import { createMidi } from "./exports";
import { createLearningNotes } from "./vocal-midi";

/** The generated bytes have to satisfy a real parser, not only our own writer. A serializer test
 *  that scans for meta events passes happily on a file no MIDI reader will open, which is exactly
 *  what happened: the MThd header carried eight data bytes where the format mandates six. */
const { Midi } = pkg as unknown as {
  Midi: new (data: Uint8Array) => { tracks: Array<{ name: string; notes: Array<{ midi: number; time: number; duration: number }> }>; header: { ppq: number; tempos: Array<{ bpm: number }>; timeSignatures: Array<{ timeSignature: number[] }> }; duration: number };
};

const note = (id: string, midi: number, startSeconds: number, durationSeconds: number) =>
  ({ id, midi, startSeconds, durationSeconds, velocity: .8, confidence: .9, pitchConfidence: .9, sourceTimestampSeconds: startSeconds });

const notes = createLearningNotes([note("a", 67, 0, .5), note("b", 69, .6, .5), note("c", 71, 1.2, .8)]);
const aligned = alignLyricsToNotes("მზეო თიბათვისა\nშენ სულ", notes);
/** @tonejs/midi reads from a standalone buffer, so the view is copied rather than passed through. */
const parse = (data: Uint8Array) => { const copy = new Uint8Array(data.length); copy.set(data); return new Midi(copy); };

describe("generated MIDI files", () => {
  it("writes a six-byte MThd chunk declaring one track and 480 ppq", () => {
    const data = createMidi(notes, null, { bpm: 96 });
    expect(new TextDecoder("latin1").decode(data.slice(0, 4))).toBe("MThd");
    expect([...data.slice(4, 14)]).toEqual([0, 0, 0, 6, 0, 0, 0, 1, 0x01, 0xe0]);
    expect(new TextDecoder("latin1").decode(data.slice(14, 18))).toBe("MTrk");
  });

  it("is readable by a standard parser, with the notes and tempo it was given", () => {
    const midi = parse(createMidi(notes, null, { bpm: 96, trackName: "Vocal Melody" }));
    expect(midi.header.ppq).toBe(480);
    expect(Math.round(midi.header.tempos[0].bpm)).toBe(96);
    expect(midi.header.timeSignatures[0].timeSignature).toEqual([4, 4]);
    expect(midi.tracks[0].name).toBe("Vocal Melody");
    expect(midi.tracks[0].notes.map((item) => item.midi)).toEqual([67, 69, 71]);
    expect(midi.tracks[0].notes[1].time).toBeCloseTo(.6, 2);
    expect(midi.tracks[0].notes[2].duration).toBeCloseTo(.8, 2);
  });

  it("carries standard Lyric meta events alongside the notes", () => {
    const data = createMidi(aligned.notes, aligned.alignment, { bpm: 96, includeLyrics: true });
    const lyrics: string[] = [];
    for (let index = 0; index + 2 < data.length; index += 1) {
      if (data[index] !== 0xff || data[index + 1] !== 0x05) continue;
      const length = data[index + 2];
      lyrics.push(new TextDecoder("utf8").decode(data.subarray(index + 3, index + 3 + length)));
    }
    expect(lyrics.length).toBeGreaterThan(0);
    expect(lyrics.join(" ")).toContain("მზეო");
    // The file still parses with the lyric events present.
    expect(parse(data).tracks[0].notes.length).toBe(aligned.notes.length);
  });

  it("keeps an empty melody parseable instead of writing a truncated file", () => {
    const midi = parse(createMidi([], null, { bpm: 120 }));
    expect(midi.tracks.length).toBeGreaterThan(0);
    expect(midi.tracks[0].notes).toHaveLength(0);
  });
});
